apiVersion: skaffold/v1beta11
kind: Config

build:
  artifacts:
  - image: hitsujihaneta/skaffold-example-frontend
    context: php-redis
  - image: hitsujihaneta/skaffold-example-redis-slave
    context: redis-slave
  local:
    push: false

test:
  - image: hitsujihaneta/skaffold-example-frontend
    structureTests:
      - './structure-test/*'

deploy:
  kubectl:
    manifests:
    - frontend-*.yaml
    - redis-master-*.yaml
    - redis-slave-*.yaml
    - guestbook-ingress.yaml